# Generated by Django 6.0 on 2026-01-01 04:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_usergame_options_remove_usergame_steamid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usergame',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Гра користувача', 'verbose_name_plural': 'Ігри користувачів'},
        ),
        migrations.AlterField(
            model_name='usergame',
            name='appid',
            field=models.PositiveIntegerField(verbose_name='AppID гри (Steam)'),
        ),
        migrations.AlterField(
            model_name='usergame',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Відгук/коментар'),
        ),
        migrations.AlterField(
            model_name='usergame',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата створення'),
        ),
        migrations.AlterField(
            model_name='usergame',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Оцінка (1–10)'),
        ),
        migrations.AlterField(
            model_name='usergame',
            name='status',
            field=models.CharField(blank=True, choices=[('playing', 'Граю'), ('completed', 'Пройдено'), ('planned', 'У планах'), ('dropped', 'Відкладено'), ('not_played', 'Не грав')], max_length=20, null=True, verbose_name='Статус проходження'),
        ),
        migrations.AlterField(
            model_name='usergame',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Останнє оновлення'),
        ),
        migrations.AlterField(
            model_name='usergame',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_games', to=settings.AUTH_USER_MODEL, verbose_name='Користувач'),
        ),
    ]
