# Generated by Django 6.0 on 2026-01-01 04:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_usergame_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usergame',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RemoveField(
            model_name='usergame',
            name='steamid',
        ),
        migrations.AlterField(
            model_name='usergame',
            name='appid',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='usergame',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='usergame',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usergame',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='usergame',
            name='status',
            field=models.CharField(blank=True, choices=[('completed', 'Пройдено'), ('playing', 'Граю'), ('planned', 'У планах'), ('dropped', 'Відкладено'), ('not_played', 'Не грав')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usergame',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='usergame',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_games', to=settings.AUTH_USER_MODEL),
        ),
    ]
