# Generated by Django 6.0 on 2026-01-02 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_alter_usergame_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlist',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
