# Generated by Django 6.0 on 2025-12-12 05:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steamid', models.CharField(help_text='SteamID64 of the user (for additional safety and queries)', max_length=17)),
                ('appid', models.PositiveIntegerField(help_text='Steam AppID of the game')),
                ('status', models.CharField(blank=True, choices=[('completed', 'Completed'), ('playing', 'Playing'), ('dropped', 'Dropped'), ('not_played', 'Not Played')], help_text='User-defined completion status', max_length=20, null=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='User rating from 1 to 5 stars', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, help_text="User's personal comment or review about the game")),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of the last update')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('user', models.ForeignKey(help_text='The authenticated user who owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='user_games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Game',
                'verbose_name_plural': 'User Games',
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'appid')},
            },
        ),
    ]
