# Generated by Django 6.0 on 2025-12-13 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergame',
            name='status',
            field=models.CharField(blank=True, choices=[('completed', 'Пройдено'), ('playing', 'Граю'), ('planned', 'У планах'), ('dropped', 'Відкладено'), ('not_played', 'Не грав')], help_text='User-defined completion status', max_length=20, null=True),
        ),
    ]
