# Generated by Django 6.0 on 2026-01-02 04:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_usergame_options_alter_usergame_appid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergame',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
