# Generated by Django 6.0 on 2026-01-02 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_userlist_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergame',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
