# Generated by Django 6.0 on 2026-01-02 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_usergame_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergame',
            name='name',
        ),
    ]
