# Generated by Django 6.0 on 2026-01-03 06:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usergame',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='usergame',
            name='rawg_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usergame',
            name='appid',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='usergame',
            unique_together={('user', 'rawg_id')},
        ),
    ]
