# Generated by Django 6.0 on 2026-01-19 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_usergame_unique_together_usergame_rawg_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergame',
            name='appid',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар'),
        ),
    ]
